### ISSUE TITLE
로그인 해보면 "내부 에러가 발생했습니다" 이 메시지 받아요.

### ISSUE THREAD

**Issue by aero31aero** [KiwiTalk/KiwiTalk#2100]
### Current behavior

한국어 잘 못 하는데 kiwitalk 쓰기 좀 어려운 것 같아요. 그래도 이것을 문제처럼 이에요.

로그인 하기 시작해서 핸드폰에서 [new device registration] code 받아서 [Login notification]도 받아요. 근데 kiwitalk에서 "내부 에러가 발생했습니다"라는 메시지 보여요.

닫고 다시 시작 하면 그냥 "자동 로그인이 실패 했습니다"라는 메시지 보여요.

도와줄 수 있으면 감사해요!

### Step to reproduce

이매일랑 로그인 해보세요.

### OS, or Other Environments

OS: Archlinux
System Webview version: NA?
Using Development build: No
Kiwitalk version: [AUR package 0.2.3](https://aur.archlinux.org/packages/kiwitalk-bin)

### Additional Notes

인도에서 살아요. 한국밖에 못 쓸리가 있을 수 있어요?... 그리고 영어를 하면 돼요?

### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.
- [X] I have provided all required informations.

**Comment by RanolP** [comment]
Unfortunately due to our limited resources, we currently do not offer any translation/internationalization now. Also, the product is very immature and most things can be subject to change. So we do not have a plan to translate yet. You could contribute translation files and suggest better i18n infra. We'll be happy with your contribution. But as the task's priority is very low at this time, the PRs could not be reviewed/merged rapidly. Anyway, thanks for your participation!

**Comment by JellyBrick** [comment]
Since we are refactoring the entire code, we expect this issue will be resolved in 0.3.x or 0.4.x.

**Comment by JellyBrick** [comment]
Are you still experiencing this issue?

**Comment by aero31aero** [comment]
Yeah, sorry... I've been trying the latest dev builds and haven't faced it in a while. It did sort of gp away magically, as I described on the Discord. I'll close this for now, but in case I see it again I'll reopen/file a new one. Thanks!
